/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC22x
 * - package : TQFP80
 */

/*
 * Instructions on how to build this generated file and the Infineon's iLLD library with the TASKING  VX-toolset
 * for TriCore:
 * 1. Provide appropriate include paths to the compiler (-I option) to locate the iLLD library.
 * 2. Provide macro IFX_CFG_USE_COMPILER_DEFAULT_LINKER to the compiler (-D option) to prevent multiple
 *    definitions of symbol '_START' (in cstart.c and IfxCpu_CStart0.c).
 * 3. Disable compiler option 'Automatic inclusion of .sfr files' (-H option) to prevent macros to be redefined.
 */

#ifndef AURIX_PIN_MAPPINGS_H_
#define AURIX_PIN_MAPPINGS_H_

/* Infineon's iLLD library include files */

#include <Port/Io/IfxPort_Io.h>

#include <_PinMap/IfxPort_PinMap.h>


/* Symbolic names for GPIO ports */

// p00_0
#define IFXCFG_PORT_LED5                        IfxPort_P00_0
#define IFXCFG_PORT_LED5_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED5_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_0
#define IFXCFG_PORT_BUZZ                        IfxPort_P02_0
#define IFXCFG_PORT_BUZZ_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_BUZZ_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_1
#define IFXCFG_PORT_POWER                       IfxPort_P02_1
#define IFXCFG_PORT_POWER_MODE                  IfxPort_Mode_inputPullUp
#define IFXCFG_PORT_POWER_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed1

// p02_6
#define IFXCFG_PORT_LED2                        IfxPort_P02_6
#define IFXCFG_PORT_LED2_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED2_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_7
#define IFXCFG_PORT_LED3                        IfxPort_P02_7
#define IFXCFG_PORT_LED3_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED3_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p02_8
#define IFXCFG_PORT_LED4                        IfxPort_P02_8
#define IFXCFG_PORT_LED4_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_LED4_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p11_3
#define IFXCFG_PORT_DIR                         IfxPort_P11_3
#define IFXCFG_PORT_DIR_MODE                    IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_DIR_PAD_DRIVER              IfxPort_PadDriver_cmosAutomotiveSpeed4

// p11_9
#define IFXCFG_PORT_DTS                         IfxPort_P11_9
#define IFXCFG_PORT_DTS_MODE                    IfxPort_Mode_inputPullDown
#define IFXCFG_PORT_DTS_PAD_DRIVER              IfxPort_PadDriver_cmosAutomotiveSpeed1

// p20_11
#define IFXCFG_PORT_RGB1                        IfxPort_P20_11
#define IFXCFG_PORT_RGB1_MODE                   IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_RGB1_PAD_DRIVER             IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_12
#define IFXCFG_PORT_GPIO1                       IfxPort_P20_12
#define IFXCFG_PORT_GPIO1_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO1_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_13
#define IFXCFG_PORT_GPIO2                       IfxPort_P20_13
#define IFXCFG_PORT_GPIO2_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO2_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_14
#define IFXCFG_PORT_GPIO3                       IfxPort_P20_14
#define IFXCFG_PORT_GPIO3_MODE                  IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_GPIO3_PAD_DRIVER            IfxPort_PadDriver_cmosAutomotiveSpeed4


/* Generic port I/O configuration */

#define IFXCFG_P00_0_IO_CONFIG                  { &IFXCFG_PORT_LED5, IFXCFG_PORT_LED5_MODE, IFXCFG_PORT_LED5_PAD_DRIVER }
#define IFXCFG_P02_0_IO_CONFIG                  { &IFXCFG_PORT_BUZZ, IFXCFG_PORT_BUZZ_MODE, IFXCFG_PORT_BUZZ_PAD_DRIVER }
#define IFXCFG_P02_1_IO_CONFIG                  { &IFXCFG_PORT_POWER, IFXCFG_PORT_POWER_MODE, IFXCFG_PORT_POWER_PAD_DRIVER }
#define IFXCFG_P02_6_IO_CONFIG                  { &IFXCFG_PORT_LED2, IFXCFG_PORT_LED2_MODE, IFXCFG_PORT_LED2_PAD_DRIVER }
#define IFXCFG_P02_7_IO_CONFIG                  { &IFXCFG_PORT_LED3, IFXCFG_PORT_LED3_MODE, IFXCFG_PORT_LED3_PAD_DRIVER }
#define IFXCFG_P02_8_IO_CONFIG                  { &IFXCFG_PORT_LED4, IFXCFG_PORT_LED4_MODE, IFXCFG_PORT_LED4_PAD_DRIVER }
#define IFXCFG_P11_3_IO_CONFIG                  { &IFXCFG_PORT_DIR, IFXCFG_PORT_DIR_MODE, IFXCFG_PORT_DIR_PAD_DRIVER }
#define IFXCFG_P11_9_IO_CONFIG                  { &IFXCFG_PORT_DTS, IFXCFG_PORT_DTS_MODE, IFXCFG_PORT_DTS_PAD_DRIVER }
#define IFXCFG_P20_11_IO_CONFIG                 { &IFXCFG_PORT_RGB1, IFXCFG_PORT_RGB1_MODE, IFXCFG_PORT_RGB1_PAD_DRIVER }
#define IFXCFG_P20_12_IO_CONFIG                 { &IFXCFG_PORT_GPIO1, IFXCFG_PORT_GPIO1_MODE, IFXCFG_PORT_GPIO1_PAD_DRIVER }
#define IFXCFG_P20_13_IO_CONFIG                 { &IFXCFG_PORT_GPIO2, IFXCFG_PORT_GPIO2_MODE, IFXCFG_PORT_GPIO2_PAD_DRIVER }
#define IFXCFG_P20_14_IO_CONFIG                 { &IFXCFG_PORT_GPIO3, IFXCFG_PORT_GPIO3_MODE, IFXCFG_PORT_GPIO3_PAD_DRIVER }


/* Initialization routines */

extern void gpio_init_pins(void);


#endif /* AURIX_PIN_MAPPINGS_H_ */
