/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC22x
 * - package : TQFP80
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P00_0_IO_CONFIG,
    IFXCFG_P02_0_IO_CONFIG,
    IFXCFG_P02_1_IO_CONFIG,
    IFXCFG_P02_6_IO_CONFIG,
    IFXCFG_P02_7_IO_CONFIG,
    IFXCFG_P02_8_IO_CONFIG,
    IFXCFG_P11_3_IO_CONFIG,
    IFXCFG_P11_9_IO_CONFIG,
    IFXCFG_P20_11_IO_CONFIG,
    IFXCFG_P20_12_IO_CONFIG,
    IFXCFG_P20_13_IO_CONFIG,
    IFXCFG_P20_14_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}

